ALCABITIUS.title=Alcabitius
AXIAL_ROTATION.title=Axial Rotation System
CAMPANUS.title=Campanus
EQUAL.title=Equal
WHOLE_SIGN.title=Whole Sign
HORIZONTAL.title=Horizontal or Azimuthal System
KOCH.title=Koch
PLACIDUS.title=Placidus
PORPHYRIUS.title=Porphyrius
REGIOMONTANUS.title=Regiomontanus
VEHLOW_EQUAL.title=Vehlow Equal
MERIDIAN.title=Meridian
