package destiny.core

import destiny.core.EventCategory.*


enum class EventCategory {
  ROMANCE_AND_MARRIAGE,         // 感情與婚姻
  FAMILY_AND_RELATIVES,         // 家庭與家族
  CAREER_AND_ACADEMICS,         // 事業與學業
  FINANCE_AND_ASSETS,           // 財務與資產
  HEALTH_AND_ACCIDENTS,         // 健康與意外
  REPUTATION_AND_RELATIONSHIPS, // 名聲與人際
  SPIRITUAL_AND_RELIGIOUS,      // 心靈與宗教
  OTHERS                        // 其他
}

/**
 * 定義所有可選的具體生命事件。
 * @param category 事件所屬的類別
 */
enum class EventType(
  val category: EventCategory
) {
  // 感情與婚姻
  RELATIONSHIP_START(ROMANCE_AND_MARRIAGE),       // 開始重要戀情
  ENGAGEMENT_MARRIAGE(ROMANCE_AND_MARRIAGE),      // 訂婚／結婚
  RELATIONSHIP_END(ROMANCE_AND_MARRIAGE),         // 分手／離婚
  RELATIONSHIP_CRISIS(ROMANCE_AND_MARRIAGE),      // 外遇／關係危機

  // 家庭與家族
  CHILD_BIRTH(FAMILY_AND_RELATIVES),              // 生子／收養子女
  FAMILY_LOSS(FAMILY_AND_RELATIVES),              // 親人亡故
  FAMILY_CONFLICT(FAMILY_AND_RELATIVES),          // 家庭衝突
  RELOCATION_IMMIGRATION(FAMILY_AND_RELATIVES),   // 搬家／移民

  // 事業與學業
  START_HIGHER_EDUCATION(CAREER_AND_ACADEMICS), // 進入高等教育
  GRADUATION(CAREER_AND_ACADEMICS),             // 畢業
  ENTREPRENEURSHIP(CAREER_AND_ACADEMICS),       // 創業
  PROMOTION_APPOINTMENT(CAREER_AND_ACADEMICS),  // 升遷／獲得重要職位
  MAJOR_ACHIEVEMENT(CAREER_AND_ACADEMICS),      // 重大成就／得獎
  CAREER_SETBACK(CAREER_AND_ACADEMICS),         // 事業挫敗
  UNEMPLOYMENT_LAYOFF(CAREER_AND_ACADEMICS),    // 失業／資遣
  CAREER_CHANGE(CAREER_AND_ACADEMICS),          // 轉換跑道
  STEP_DOWN_RESIGN(CAREER_AND_ACADEMICS),       // 下台／請辭
  RETIREMENT(CAREER_AND_ACADEMICS),             // 退休

  // 財務與資產
  MAJOR_FINANCIAL_GAIN(FINANCE_AND_ASSETS),   // 財務收入
  MAJOR_FINANCIAL_LOSS(FINANCE_AND_ASSETS),   // 破產／重大虧損
  INHERITANCE_WINDFALL(FINANCE_AND_ASSETS),   // 繼承遺產／大筆獲利
  REAL_ESTATE_PURCHASE(FINANCE_AND_ASSETS),   // 買房
  REAL_ESTATE_SALE(FINANCE_AND_ASSETS),       // 賣房

  // 健康與意外
  MAJOR_ILLNESS(HEALTH_AND_ACCIDENTS),          // 確診重大疾病
  MAJOR_SURGERY(HEALTH_AND_ACCIDENTS),          // 大型手術
  HEALTH_RECOVERY(HEALTH_AND_ACCIDENTS),        // 健康恢復
  SERIOUS_ACCIDENT(HEALTH_AND_ACCIDENTS),       // 重大意外 (非人為蓄意)
  VICTIM_OF_ATTACK(HEALTH_AND_ACCIDENTS),       // 遭攻擊／受害

  // 名聲與人際
  REPUTATION_CRISIS(REPUTATION_AND_RELATIONSHIPS),        // 名聲危機
  REPUTATION_RESTORED(REPUTATION_AND_RELATIONSHIPS),      // 名譽恢復
  GOING_VIRAL(REPUTATION_AND_RELATIONSHIPS),              // 爆紅
  LEGAL_CHALLENGE(REPUTATION_AND_RELATIONSHIPS),          // 法律危機
  FAVORABLE_LEGAL_OUTCOME(REPUTATION_AND_RELATIONSHIPS),  // 有利的法律結果
  LIBERATION_OR_RELEASE(REPUTATION_AND_RELATIONSHIPS),    // 重獲自由／釋放
  COMPETITION_WIN(REPUTATION_AND_RELATIONSHIPS),          // 競逐得勝
  COMPETITION_LOSS(REPUTATION_AND_RELATIONSHIPS),         // 競逐失利 (如選舉、商業奪權)
  PUBLIC_CONFRONTATION(REPUTATION_AND_RELATIONSHIPS),     // 公開對抗／控訴
  FALLING_OUT(REPUTATION_AND_RELATIONSHIPS),              // 與摯友／夥伴決裂
  RECONCILIATION(REPUTATION_AND_RELATIONSHIPS),           // 和解
  MEET_KEY_MENTOR(REPUTATION_AND_RELATIONSHIPS),          // 遇到重要導師
  VIOLENT_OFFENDER(REPUTATION_AND_RELATIONSHIPS),         // 暴力行為／加害他人

  // 心靈與宗教
  BAPTISM(SPIRITUAL_AND_RELIGIOUS),            // 受洗
  CONVERSION(SPIRITUAL_AND_RELIGIOUS),          // 宗教皈依
  LEAVE_RELIGION(SPIRITUAL_AND_RELIGIOUS),      // 退教
  ORDINATION_MONASTIC(SPIRITUAL_AND_RELIGIOUS),// 剃度出家／受戒
  SPIRITUAL_AWAKENING(SPIRITUAL_AND_RELIGIOUS), // 精神覺醒
  PILGRIMAGE(SPIRITUAL_AND_RELIGIOUS),          // 朝聖
  RELIGIOUS_CEREMONY(SPIRITUAL_AND_RELIGIOUS),  // 其他重大宗教儀式

  // 其他
  OTHERS(EventCategory.OTHERS), // 其他事件
}
